# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Subscription1(1)(ac42974e-97b9-4f70-a1e9-5d82adb805b3)'
    subscriptionId: 'ac42974e-97b9-4f70-a1e9-5d82adb805b3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'arm-demo-prod'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'function-app.json'
    csmParametersFile: 'function-app.paramiters.json'
    deploymentMode: 'Incremental'
    csmFile: 'web-app-sql.json'
    csmParametersFile: 'web-app-sql.parameters.json'
    deploymentMode: 'Validation'
